server {
    listen 80 default_server;
    server_name _;
    return 444;
}

server {
    listen 80;
    server_name calculadora.cairostudio.cu;
    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name lona.cairostudio.cu;
    location / {
        proxy_pass http://127.0.0.1:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name 10.10.10.25 portal.cairostudio.cu;
    root /opt/cairostudiokit/tools/portal;
    index index.html;
}