"""etiqueta favorita: hash para deduplicación

Revision ID: 1383c5cb3e70
Revises: 79794b0cd400
Create Date: 2026-09-17 15:46:01.410097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1383c5cb3e70'
down_revision = '79794b0cd400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etiquetas_favoritas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_archivo', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_etiquetas_favoritas_hash_archivo'), ['hash_archivo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etiquetas_favoritas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etiquetas_favoritas_hash_archivo'))
        batch_op.drop_column('hash_archivo')

    # ### end Alembic commands ###
