"""refactor etiquetas favoritas minimalista

Revision ID: 79794b0cd400
Revises: b0654f3b4698
Create Date: 2026-09-16 19:24:28.042860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79794b0cd400'
down_revision = 'b0654f3b4698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etiquetas_favoritas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ancho_cm', sa.Float(), nullable=False),
    sa.Column('alto_cm', sa.Float(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('archivo_nombre', sa.String(length=255), nullable=True),
    sa.Column('archivo_ruta', sa.String(length=500), nullable=True),
    sa.Column('archivo_tipo', sa.String(length=80), nullable=True),
    sa.Column('archivo_tamano', sa.Integer(), nullable=True),
    sa.Column('veces_usado', sa.Integer(), nullable=False),
    sa.Column('ultima_vez_usado', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('etiquetas_favoritas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etiquetas_favoritas_client_id'), ['client_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etiquetas_favoritas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etiquetas_favoritas_client_id'))

    op.drop_table('etiquetas_favoritas')
    # ### end Alembic commands ###
