"""Añadir ancho_util, merma_porcentaje a Producto y tipo_ajuste a Movimiento

Revision ID: 79e5ca40ddea
Revises: 
Create Date: 2026-09-09 17:23:35.662328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e5ca40ddea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_ajuste', sa.String(length=20), nullable=True))

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ancho_util', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('merma_porcentaje', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('merma_porcentaje')
        batch_op.drop_column('ancho_util')

    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.drop_column('tipo_ajuste')

    # ### end Alembic commands ###
