"""Añadir modelo ConteoSemanal

Revision ID: 8979a82c7f6c
Revises: ab25abe17607
Create Date: 2026-09-14 14:34:15.200275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8979a82c7f6c'
down_revision = 'ab25abe17607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conteos_semanales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('semana', sa.String(length=10), nullable=False),
    sa.Column('stock_sistema_unidades', sa.Float(), nullable=True),
    sa.Column('stock_sistema_metros', sa.Float(), nullable=True),
    sa.Column('stock_fisico_unidades', sa.Float(), nullable=True),
    sa.Column('stock_fisico_metros', sa.Float(), nullable=True),
    sa.Column('diferencia_unidades', sa.Float(), nullable=True),
    sa.Column('diferencia_metros', sa.Float(), nullable=True),
    sa.Column('merma_operativa_semana_m2', sa.Float(), nullable=True),
    sa.Column('merma_imprevista_metros', sa.Float(), nullable=True),
    sa.Column('merma_imprevista_m2', sa.Float(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conteos_semanales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conteos_semanales_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_conteos_semanales_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conteos_semanales_semana'), ['semana'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conteos_semanales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conteos_semanales_semana'))
        batch_op.drop_index(batch_op.f('ix_conteos_semanales_producto_id'))
        batch_op.drop_index(batch_op.f('ix_conteos_semanales_fecha'))

    op.drop_table('conteos_semanales')
    # ### end Alembic commands ###
