"""Añadir gap_panno_cm a Producto

Revision ID: ab25abe17607
Revises: f952b01a88c0
Create Date: 2026-09-11 09:12:10.637553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab25abe17607'
down_revision = 'f952b01a88c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gap_panno_cm', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('gap_panno_cm')

    # ### end Alembic commands ###
