"""Etiquetas favoritas por cliente

Revision ID: b0654f3b4698
Revises: 8979a82c7f6c
Create Date: 2026-09-16 19:09:05.345422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0654f3b4698'
down_revision = '8979a82c7f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etiquetas_favoritas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ancho_cm', sa.Float(), nullable=False),
    sa.Column('alto_cm', sa.Float(), nullable=False),
    sa.Column('precio_m2', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('cantidad_sugerida', sa.Float(), nullable=True),
    sa.Column('mesa', sa.Boolean(), nullable=True),
    sa.Column('girar', sa.Boolean(), nullable=True),
    sa.Column('auto_girar', sa.Boolean(), nullable=True),
    sa.Column('centrar', sa.Boolean(), nullable=True),
    sa.Column('ancho_util_override', sa.Float(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('archivo_nombre', sa.String(length=255), nullable=True),
    sa.Column('archivo_ruta', sa.String(length=500), nullable=True),
    sa.Column('archivo_tipo', sa.String(length=80), nullable=True),
    sa.Column('veces_usado', sa.Integer(), nullable=True),
    sa.Column('ultima_vez_usado', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('etiquetas_favoritas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etiquetas_favoritas_client_id'), ['client_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etiquetas_favoritas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etiquetas_favoritas_client_id'))

    op.drop_table('etiquetas_favoritas')
    # ### end Alembic commands ###
