"""Eliminar ancho_util de Producto

Revision ID: f952b01a88c0
Revises: 79e5ca40ddea
Create Date: 2026-09-10 16:25:49.201289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f952b01a88c0'
down_revision = '79e5ca40ddea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('ancho_util')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ancho_util', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
