"""empleados: activo, fecha_baja, tipo_pago, salario_fijo_mensual

Revision ID: f9a1e246c514
Revises: 1a2e2b74bbfe
Create Date: 2026-10-05 10:49:38.893303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a1e246c514'
down_revision = '1a2e2b74bbfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('fecha_baja', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('tipo_pago', sa.String(length=20), server_default='hora', nullable=False))
        batch_op.add_column(sa.Column('salario_fijo_mensual', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.drop_column('salario_fijo_mensual')
        batch_op.drop_column('tipo_pago')
        batch_op.drop_column('fecha_baja')
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
